package net.rezmason.wireworld.brains;

extern class BaseModel extends flash.events.EventDispatcher, implements net.rezmason.wireworld.IModel {
	public function new():Void;
	public function baseGraphics():flash.display.Graphics;
	public function credit():String;
	public function eraseRect(rect:flash.geom.Rectangle):Void;
	public function generation():Float;
	public function getState(__x:Int, __y:Int):UInt;
	public function headData():flash.display.BitmapData;
	public function headGraphics():flash.display.Graphics;
	public function heatGraphics():flash.display.Graphics;
	public function height():Int;
	public function implementsOverdrive():Bool;
	public function init(txt:String, isMCell:Bool):Void;
	public function overdriveActive():Bool;
	public function refresh(flags:Int):Void;
	public function reset():Void;
	public function setBounds(top:Int, left:Int, bottom:Int, right:Int):Void;
	public function set_overdriveActive(value:Bool):Void;
	public function tailData():flash.display.BitmapData;
	public function tailGraphics():flash.display.Graphics;
	public function update():Void;
	public function width():Int;
	public function wireData():flash.display.BitmapData;
	public function wireGraphics():flash.display.Graphics;
	private var _baseGraphics:flash.display.Graphics;
	private var _credit:String;
	private var _generation:UInt;
	private var _headData:flash.display.BitmapData;
	private var _headGraphics:flash.display.Graphics;
	private var _heatData:flash.display.BitmapData;
	private var _heatGraphics:flash.display.Graphics;
	private var _height:Int;
	private var _tailData:flash.display.BitmapData;
	private var _tailGraphics:flash.display.Graphics;
	private var _width:Int;
	private var _wireData:flash.display.BitmapData;
	private var _wireGraphics:flash.display.Graphics;
	private var activeCorner:flash.geom.Point;
	private var activeRect:flash.geom.Rectangle;
	private var bottomBound:Int;
	private var bound:flash.geom.Rectangle;
	private var importer:Importer;
	private var leftBound:Int;
	private var rightBound:Int;
	private var topBound:Int;
	private var totalNodes:Int;
	
	function addNode(__x:Int, __y:Int, __state:Int):Void;
	function colorOf(input:Float):UInt;
	function drawBackground(graphicsObject:flash.display.Graphics, w:Float, h:Float, color:Int):Void;
	function drawData(graphicsObject:flash.display.Graphics, rect:flash.geom.Rectangle, data:flash.display.BitmapData):Void;
	function finishExtraction(event:flash.events.Event):Void;
	function finishParse(event:flash.events.Event):Void;
	function heatColorOf(input:Float):UInt;
	function refreshHeat(fully:Int):Void;
	function refreshImage(fully:Int, freshTails:Int):Void;
}
